In [1]:
import numpy as np

# DataTypes and attributes

In [2]:
#Numpy's main datatype is ndarray
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2= np.array([[1,2.0,3.3],[4,5,6.5]])

a3= np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]])

In [5]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [6]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [8]:
a1.shape

(3,)

In [9]:
a2.shape

(2, 3)

In [10]:
a3.shape

(2, 3, 3)

In [11]:
# number of dimensions
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [13]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [14]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [15]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [19]:
#Create a Dataframe from a Numpy array

import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

# 2. Creating arrays

In [21]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [22]:
sample_array.dtype

dtype('int32')

In [38]:
#numpy.ones & zeros Return a new array of given shape and type, filled with ones & zeros.
ones = (3,3)
zeros = (3,3)

In [40]:
np.ones(ones)
np.zeros(zeros)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [42]:
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [43]:
random_array = np.random.randint(0,10, size=(3,5))
random_array

array([[8, 3, 3, 8, 2],
       [2, 2, 1, 2, 8],
       [0, 1, 3, 9, 2]])

In [44]:
random_array.size

15

In [46]:
random_array.shape

(3, 5)

In [47]:
random_array_2 = np.random.random((5,3))
random_array_2

array([[0.86997288, 0.80330235, 0.91426871],
       [0.15079834, 0.01962403, 0.24465365],
       [0.32603972, 0.8827147 , 0.51505418],
       [0.41962421, 0.05348382, 0.56991412],
       [0.22172119, 0.69584248, 0.0499238 ]])

In [49]:
random_array_3 = np.random.rand(5,3)
random_array_3

array([[0.81272103, 0.0255743 , 0.08067463],
       [0.98086946, 0.09244148, 0.55769109],
       [0.10944437, 0.16559045, 0.46032321],
       [0.6918518 , 0.20831294, 0.40329438],
       [0.31077757, 0.92010115, 0.29855404]])

In [64]:
# Pseudo-random numbers
np.random.seed(seed=1)
random_array_4 = np.random.randint(10, size=(5,3))
random_array_4

array([[5, 8, 9],
       [5, 0, 0],
       [1, 7, 6],
       [9, 2, 4],
       [5, 2, 4]])

In [70]:
np.random.seed(7)
random_array_5 = np.random.random((5,3))
random_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

# 3. Viewing Arrays and Matrices

In [72]:
np.unique(random_array_4)

array([0, 1, 2, 4, 5, 6, 7, 8, 9])

In [73]:
a1

array([1, 2, 3])

In [74]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [75]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [76]:
a1[0]

1

In [81]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [82]:
a3[:2,:2,:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [84]:
a4= np.random.randint(10, size=(2,3,4,5))
a4

array([[[[3, 5, 8, 8, 7],
         [5, 0, 0, 2, 8],
         [9, 6, 4, 9, 7],
         [3, 3, 8, 3, 0]],

        [[1, 0, 0, 6, 7],
         [7, 9, 3, 0, 7],
         [7, 7, 0, 5, 4],
         [3, 1, 3, 1, 3]],

        [[4, 3, 1, 9, 5],
         [9, 1, 2, 3, 2],
         [2, 5, 7, 3, 0],
         [9, 9, 3, 4, 5]]],


       [[[3, 0, 4, 8, 6],
         [7, 2, 7, 3, 8],
         [6, 6, 5, 6, 5],
         [7, 1, 5, 4, 4]],

        [[9, 9, 0, 6, 2],
         [6, 8, 2, 4, 1],
         [6, 1, 5, 1, 6],
         [9, 8, 6, 5, 9]],

        [[7, 5, 4, 9, 6],
         [8, 1, 5, 5, 8],
         [3, 7, 7, 9, 4],
         [7, 5, 9, 6, 2]]]])

In [85]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

# 4. Manipulating & comparing arrays

## Artihmeric

In [87]:
ones

(3, 3)

In [88]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [91]:
a1/ones

array([1., 2., 3.])