In [29]:
import numpy as np

In [30]:
a1=np.array([1,2,3])
a1

array([1, 2, 3])

In [31]:
type(a1)

numpy.ndarray

In [32]:
a2=np.array([[1,2,3],
           [4.3,5.5,6.5]])
a2

array([[1. , 2. , 3. ],
       [4.3, 5.5, 6.5]])

In [33]:
a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
               [[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]]])
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [34]:
a1.shape

(3,)

In [35]:
a2.shape

(2, 3)

In [36]:
a3.shape

(2, 3, 3)

In [37]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [38]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [39]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [40]:
import pandas as pd
df= pd.DataFrame(a1)
df

0
0  1
1  2
2  3